addons:
  apt:
    packages:
      - swig

notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - scripts/compile_swig.sh
  - docker pull $DOCKER_IMAGE

script:
  - docker run -v `pwd`:/code $DOCKER_IMAGE /code/scripts/docker_build.sh
  - ls wheelhouse/
