addons:
  apt:
    packages:
      - swig
notifications:
  email: false
matrix:
  exclude:
    - python: 3.5
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           PLAT=manylinux1_i686
install:
  - docker pull $DOCKER_IMAGE
script:
  - docker run --rm -v `pwd`:/code $DOCKER_IMAGE
  - $PRE_CMD /code/scripts/docker_build.sh
  - ls dist/
