addons:
  apt:
    packages:
      - swig

notifications:
  email: false

deploy:
  provider: pypi
  user: szmingyao
  password: $PYPI_PASSWORD
  skip_cleanup: true
  on:
    branch: master

language: python
# Default Python version is usually 2.7
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exlclude:
    - python: 3.5
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/code $DOCKER_IMAGE $PRE_CMD /code/scripts/docker_build.sh    ; fi
  - ls wheelhouse/