addons:
  apt:
    packages:
    - swig
notifications:
  email: false
deploy:
  provider: pypi
  user: szmingyao
  password:
    secure: d5LserlOyEK48JzCVdfCGBHNq2Dos+UZLR5CckjyY6Gy4J/s+wIseNOx+vVn1VcEwfSUdiOj8h33reciCnjTimZX+hT5kUWcV1uSizUaqh2TFYWzVrD6qRRfAR3afUQpnpvGyLm56kS7ys65nHbIdvmaY11iJYjMgp3f9p+TPCi9015G0LxsRY5+bBFq1Ana8CXhXv3BX4Bg73YU13pgSNQPocCi5YzuBlz1M5mu3FfDocfokHPO5iRbFQB12IUctNJx1bdLlqvwZ71iHxurB2BrZedqUAI59eY9s1+3wjHQB8bDEnQHXgMBToDXo1tPvI2SW47k5nMYHXHGRtG2Z+MTcp0juA4QrbnvXpnPzvZhrfZ9VrXp6qtCPWhBNlb3mIkbVLi98m+KSMiT85mamnVJuD66pNLpVmsbbc42lwdfzs+co4cBat2qUPWq2NW0gcztEn6qFk9VtmoNMhFwO3nQlRONFM9OTE63vA++4Nt23kfw5HWpBG9RKkxcQuy8Q2Wwbb6FnTbMZgG/XJeOJPZhJ1/fCCe3PaOepejww0+51VbTDSbBcblyiDh70PlD1OVfMlBzUmHBMNp39mUdFRuMDithm9/sdq1FeuMB8m/ACQPXDbexCO/uDCCOvAwjnBOcfLbNg1orsm8MeideznGrRMGEgVZf6Jsz5jXXqww=
  skip_cleanup: true
  on:
    branch: master
language: python
python: 3.5
sudo: required
dist: trusty
services: docker
matrix:
  exlclude:
  - python: 3.5
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/code $DOCKER_IMAGE
  $PRE_CMD /code/scripts/docker_build.sh    ; fi
- ls dist/
