addons:
  apt:
    packages:
      - swig

notifications:
  email: false

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - sudo: required
      os: osx
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/code $DOCKER_IMAGE $PRE_CMD /code/scripts/docker_build.sh    ; fi
  - ls wheelhouse/