build_script:
  - pip install -r dev-requirements.txt
  - pip install -r test-requirements.txt
  - pip install cibuildwheel==0.9.2
  - cibuildwheel --output-dir wheelhouse
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels